"""init

Revision ID: aadef96df730
Revises: 53cfc0763a7a
Create Date: 2026-04-14 23:01:34.820253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aadef96df730'
down_revision: Union[str, Sequence[str], None] = '53cfc0763a7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('grades_subject_id_fkey'), 'grades', type_='foreignkey')
    op.drop_constraint(op.f('grades_student_id_fkey'), 'grades', type_='foreignkey')
    op.create_foreign_key(None, 'grades', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'grades', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'groups', ['name'])
    op.drop_constraint(op.f('students_group_id_fkey'), 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('subjects_teacher_id_fkey'), 'subjects', type_='foreignkey')
    op.create_foreign_key(None, 'subjects', 'teachers', ['teacher_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.create_foreign_key(op.f('subjects_teacher_id_fkey'), 'subjects', 'teachers', ['teacher_id'], ['id'])
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key(op.f('students_group_id_fkey'), 'students', 'groups', ['group_id'], ['id'])
    op.drop_constraint(None, 'groups', type_='unique')
    op.drop_constraint(None, 'grades', type_='foreignkey')
    op.drop_constraint(None, 'grades', type_='foreignkey')
    op.create_foreign_key(op.f('grades_student_id_fkey'), 'grades', 'students', ['student_id'], ['id'])
    op.create_foreign_key(op.f('grades_subject_id_fkey'), 'grades', 'subjects', ['subject_id'], ['id'])
    # ### end Alembic commands ###
